---
- name: Validate Nginx configuration
  ansible.builtin.command:
    cmd: nginx -t
  changed_when: false
  listen: Reload Nginx

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  listen: Reload Nginx