---
- name: Configure Lucee web server
  hosts: webservers
  become: true

  vars_files:
    - ../vars/database-secrets.yml
    - ../vars/atticladderph-secrets.yml

  roles:
    - role: common
      tags: [common]

    - role: database
      tags: [database]

    - role: java
      tags: [java]

    - role: commandbox
      tags: [commandbox]

    - role: nginx
      tags: [nginx]

    - role: security
      tags: [security]

    - role: certbot
      tags: [certbot]
