---
- name: Configure Lucee web server
  hosts: webservers
  become: true

  vars_files:
    - ../vars/database-secrets.yml

  roles:
    - common
    - database
    - java
    - commandbox
    - nginx
    - security
    - certbot
